# ****************************************************************************
# NOTES:
#
# In order for this to work, you must replace STAGING_ORGANISATION below
# with the name of your staging GitHub organisation, in line 53.
# You must also replace STAGING_SITE_REPOSITORY below with the name of your
# staging site repository.
#
# For example, if your staging organisation is "my-sdg-staging-org", and your
# staging site repository is "open-sdg-site-starter", then use:
#
# curl -X POST https://api.github.com/repos/my-sdg-staging-org/open-sdg-site-starter/dispatches
#
# ****************************************************************************

name: Deploy to staging

on:
  workflow_dispatch:
    # enable button to trigger workflow manually
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Build data
      run: |
        python scripts/build_data.py
    - name: Check if there are any changes to files
      id: verify_diff
      run: |
        if [[ `git status -s` ]]; then
          echo "DIFF=true" >> "$GITHUB_OUTPUT"
        else
          echo "DIFF=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Commit files
      if: steps.verify_diff.outputs.DIFF == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Add new progress measure updates"
    - name: Push changes
      if: steps.verify_diff.outputs.DIFF == 'true'
      uses: ad-m/github-push-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: ${{ github.ref }}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
    - name: Rebuild site
      run: |
        curl -X POST https://api.github.com/repos/sdg-data-canada-odd-donnees/sdg-odd-dev/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{secrets.token}}" \
        --data '{"event_type": "rebuild-staging"}'
